Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,7 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and run Docker images
+      - name: Build Docker images
         run: |
           environments="qa staging prod"
           image_list=""
@@ -41,17 +41,9 @@ jobs:
             fi
 
             image_list="${image_list} android_${env}_image"
-
-            echo "Running Docker container for image: android_${env}_image"
-            docker run -d --name container_android_${env}_image android_${env}_image
-            
-            if [ $? -ne 0 ]; then
-              echo "Failed to start Docker container for image: android_${env}_image"
-              exit 1
-            fi
           done
 
-          echo "All Docker images built and containers started successfully."
+          echo "All Docker images built successfully."
 
           echo "Image list: $image_list"
           echo "list=[$image_list]" > android_docker_image_list.txt
@@ -61,3 +53,26 @@ jobs:
         with:
           name: android-docker-image-list
           path: android_docker_image_list.txt
+
+      - name: Download image list artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: android-docker-image-list
+          path: .
+
+      - name: Run Docker containers
+        run: |
+          image_list=$(cat android_docker_image_list.txt | sed 's/list=//' | tr -d '[]')
+          IFS=', ' read -r -a images <<< "$image_list"
+
+          for image in "${images[@]}"; do
+            echo "Running Docker container for image: $image"
+            docker run -d --name container_$image $image
+            
+            if [ $? -ne 0 ]; then
+              echo "Failed to start Docker container for image: $image"
+              exit 1
+            fi
+          done
+
+          echo "All Docker containers started successfully."
